Fix #31: Uncaught TypeError: children.each is not a function
get_children_dom() may return false (see vakata/jstree#1746), so we
have to cater to that.